# -*- mode: org -*-
# Last modified: <2016-12-13 14:42:40 Tuesday by richard>
#+STARTUP: showall
#+TITLE:   README

* Useful Custom variables
#+begin_src emacs-lisp
(setq default-theme-r 'monokai
      default-source-font-r "Source Code Pro-12")
#+end_src

* packages.
All packages will be put inside a =plugin= folder.

* Install procudure.
add emacs-dealM.el to your .emacs.

ex:
#+begin_src emacs-lisp :tangle yes
(load-file "/path/to/emacs-dealM.el")
#+end_src

* Tested Environment
Mac OS X 10.10 + emacs 25.1.1

* Something out of the project.
You may need to add this thing by your own.
1. fonts:
   [[https://github.com/adobe-fonts/source-code-pro][Adobe Source Code Pro]] for English.
2. Install python package by your own:
   - for ibus-mode
     [[http://sourceforge.net/projects/python-xlib/][python-xlib][xlib]]
   - in jedi folder you need
     #+begin_src bash
     sudo pip3 install --upgrade plugins/emacs-jedi
     #+end_src

3. =pip install epc= if you want to use jedi server
4. If you have met (Error: No word lists can be found for the language "en_US".)
   install flymake lib aspell-en.
   #+begin_src bash :tangle yes
   pacman -S aspell-en
   #+end_src

* Speacial System Support

** typescript
=npm install -g clausreinke/typescript-tools=

** config HTML stuff
- If you want Flymake run, you need install tidy in your system's path.(HTML tool)
- If you use HTML5 to write pages, you can download html tidy from [[https://github.com/w3c/tidy-html5/][github]].

* TODO list:
1. try [[https://github.com/proofit404/anaconda-mode][anaconda-mode]] for python.
2. try [[http://tuhdo.github.io/c-ide.html][c-ide]] for C.


* about this project
This project is about emacs settings *ONLY* for emacs 25.1
I majorly use this settings in mac OS X/Linux, but the setting should not break windows version emacs.
