# -*- mode: org -*-
# Last modified: <2012-08-13 21:28:57 Monday by richard>
#+STARTUP: showall
#+TITLE:   README

* packages.
  All packages will be put inside a customized folder.(that is to say, I
  won't using elpa.)

* Install procudure.
  add emacs-dealM.el to your .emacs. that is to say:
  add:

  #+begin_src emacs-lisp :tangle yes
  (load-file '/path/to/emacs-dealM.el)
  #+end_src

* Testing environment.
  Archlinux(latest) + GNU Emacs 24.1.1

* Something out of the project.
  You may need to add this thing by your own.
  1. fonts:
     Inconsolata for English.
     Yayuan for Chinese.
  2. Install python package by your own:
     - for ibus-mode
       [[http://sourceforge.net/projects/python-xlib/][python-xlib][xlib]]
     - python plugins:
       [[][ropemacs]]
       [[][rope]]
       [[][pymacs]]
       [[][pyflake]]
       [[][pep8]]
       [[][pylint]]
       [[][epylint]]
       ATTENTION:You need to make the pymacs by your own.
  3. Flymake:
     You need to make pychecker.sh executable.
     #+begin_src shell
     chmod +x plugins/pychecker.sh
     #+end_src
  4. compile auctex compile settings.
  5. If you have met (Error: No word lists can be found for the language "en_US".)
     install flymake lib aspell-en.
     #+begin_src emacs-lisp :tangle yes
     # pacman -S aspell-en
     #+end_src

* Package description

** Python
    - Ropemacs (Custom) : A refactoring library
    - Auto Completion with rope (Custom) : Tested to work well with Rope
    - Flymake
      - latest flymake package
        It contains pep8, epylint, and pyflake, run them all.
    - Virtualenv : Original, In-development tool for using virtualenv in
      emacs.
    - Custom Yasnippet Snippets
    - Cython Mode: a mode for highlighting cython files
    - latest python.el (fgallina/python.el)
    - nosetests integration (nose.el)
    - It use nose tests to test buffer.

** HTML
   - If you want Flymake run, you need install tidy in your system's path.(HTML tool)

** Compile-settings
   - mainly reference the Drew Adams' package.
     package info:
     compile-settings:
     + compile+
       * compile-
         - fit-frame
         - frame-fns
       * compile (emacs built-in package)
       * misc-fns
     + compile-misc(add some addition function)
       * smart-compile

** molo-settings.
   - contains org-mode settings
   - latex-mode settings.
     + auctex settings.
   - markdown-mode settings.


* TODO list:
  1. Try helm and
     integrated to emacs if possible.
  2. Try nose and some python plugins.
  3. Add cedet 1.1 with emacs.
  4. Add grep+ plugin with emacs.

* Known bugs:
** desktop and pymacs starting bug.
    temp solve method:
    1. kill Pymacs buffer and restart emacs.
    2. disable desktop.

** Autocomplete in elisp bug.
   autocomplete will stuck emacs when using auto-complete in elisp
   especially when starts a new string.
   temp solve method:
       stop autocomplete auto-complete when editing elisp.

* about this project
  This project is about emacs settings *ONLY* for emacs 24.
  This file is another repo for compatible with emacs 24.
  This project is a emacs 24 transport version for We Master Changes.
